/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LestateRealRouteImport } from './routes/lestate-real'
import { Route as IndexRouteImport } from './routes/index'

const LestateRealRoute = LestateRealRouteImport.update({
  id: '/lestate-real',
  path: '/lestate-real',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lestate-real': typeof LestateRealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lestate-real': typeof LestateRealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lestate-real': typeof LestateRealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lestate-real'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lestate-real'
  id: '__root__' | '/' | '/lestate-real'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LestateRealRoute: typeof LestateRealRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lestate-real': {
      id: '/lestate-real'
      path: '/lestate-real'
      fullPath: '/lestate-real'
      preLoaderRoute: typeof LestateRealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LestateRealRoute: LestateRealRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
